[package]
name = "nuFAT"
version = "0.1.0"
edition = "2021"

[dependencies]
# fuse = "0.3.1" -- Deprecated (or outdated. Wait for v0.4 release)
fuser = "0.15.0"
libc = "0.2.161"
tokio = { version = "1.41.1", features = ["full"] }
