name: Style Checking

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rustfmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install libfuse
        run: sudo apt-get install -y fuse3 libfuse3-dev

      - name: Run cargo fmt
        run: cargo fmt -- --check

      - name: Run cargo clippy
        run: cargo clippy
